### ISSUE TITLE
Deconvolution after integration question

### ISSUE THREAD

**Issue by kguion1** [rohitarorayyc/SpatialTranscriptomics#1]
Hi, congrats on a great paper! 

This is the first paper I have really seen analyze multiple Visium samples from different subjects, which is also what I am trying to do. From your methods it looked like you 1) integrated with Seurat, 2) deconvoluted with CARD for celltype / cluster identification, 3) rest of analysis with integrated Visium data. 

I was looking at your code for step 2 and it looks like you created a list with all the different Visium samples.  From what I have seen Seurat integration results in one Seurat object with all the samples included. Are these re-separated samples after integration? ie between steps 1 and 2 did you have to re-separate the integrated data into their samples and re-add the images? Furthermore, is the Spatial@counts you used for CARD the integrated corrected counts or the raw counts?

Any help is greatly appreciated! Thank you.

Best,
Kate

**Comment by rohitarorayyc** [comment]
Hi Kate,

Thank you for the comment!

I'm assuming you're referring to this list:

samples = c('sample_1','sample_2','sample_3','sample_4','sample_5','sample_6','sample_7','sample_8','sample_9','sample_10','sample_11','sample_12')

I constantly use this list to loop through one Seurat object with all the samples included, to individually analyze each sample that was integrated. 

For CARD I believe I used the raw counts.

Hopefully that answers your questions,

Rohit
