### ISSUE TITLE
Cannot access spatial data

### ISSUE THREAD

**Issue by HelloWorldLTY** [rohitarorayyc/SpatialTranscriptomics#2]
Hi, I tried to access the spatial data used in this manuscript, however, there is no download link for loom or h5ad file:

http://www.[pboselab.ca/spatial_OSCC/](http://www.pboselab.ca/spatial_OSCC/)

Is it possible for me to download the spatial data you used? Thanks.

**Comment by rohitarorayyc** [comment]
Hi!

Processed files are available at Figshare: https://figshare.com/articles/dataset/Spatial_transcriptomics_reveals_distinct_and_conserved_tumor_core_and_edge_architectures_that_predict_survival_and_targeted_therapy_response_/20304456/1

Raw files are available at GEO (GSE208253): https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE208253

**Comment by HelloWorldLTY** [comment]
Thanks a lot. I successfully downloaded the data based on your provided link. However, it seems that the raw files and processed files do not match.

Firstly, the processed data do not contain spatial location information. Further more, their barcodes are different from my results.

Raw data:

![image](https://github.com/rohitarorayyc/SpatialTranscriptomics/assets/43333475/74cc5444-1b91-462b-8b9e-a56280ea7f3c)

Processed data:

![image](https://github.com/rohitarorayyc/SpatialTranscriptomics/assets/43333475/547e8524-4637-4981-9f83-b1ae455c1f6d)


Did I make anything wrong? Thanks.

**Comment by rohitarorayyc** [comment]
Processed .Robj files are provided for each of the 12 samples formatted as a Seurat object. The processed file you opened is the loom file for the scvelo analysis.

**Comment by HelloWorldLTY** [comment]
Hi, thanks for your further answer. But I find that even for the seurat object, the samples's number does not match the number in the original file:
![image](https://github.com/rohitarorayyc/SpatialTranscriptomics/assets/43333475/0c667821-3042-469e-8200-3a1ce0e896a0)

The dataset I used is sampel_12. Did I make anything wrong? Thanks.

**Comment by rohitarorayyc** [comment]
Thank you for message. I'm not too sure what the question you're asking is. Could you please clarify further?

**Comment by HelloWorldLTY** [comment]
Hi, the length of cell_id of raw data is 4k, but the r file only contains 1k cells, the difference makes me feel confused.

Moreover, it seems that the R file does not contain the spliced and unspliced information, would you please share your idea about how to load it? Thanks.

**Comment by rohitarorayyc** [comment]
I think many of these are spots which do not contain tissue in them, and also some spots that did not pass quality control.

The spliced and unspliced info can be read in using the Dynamo or Scvelo python packages.

**Comment by HelloWorldLTY** [comment]
Ok, thanks a lot. I will try to find if I can get the spliced and unspliced information.

**Comment by HelloWorldLTY** [comment]
Hi, now I think I found the things that we do not match. Actually I am interested in these codes:

```
#load loom from scvelo output
adata = scv.read('arc_outputs/countB/possorted_genome_bam_KG70A.loom', cache=True)
#load positions matrix for file
positions = pd.read_csv("position_mtx/sampleB.csv")
positions = positions.tail(positions.shape[0] -1)
positions.index = positions.index.rename("CellID")
positions["CellID"] = positions["Barcode"]
positions.drop("Barcode", inplace=True, axis=1)
positions.index = positions["CellID"]
positions['pxl_col_in_fullres'] = positions['pxl_col_in_fullres'].astype('float32')
positions['pxl_row_in_fullres'] = positions['pxl_row_in_fullres'].astype('float32')

adata.obs = adata.obs.join(positions, how="left")

adata.obsm['X_umap'] = adata.obs[
            ['pxl_row_in_fullres', 'pxl_col_in_fullres']
        ].to_numpy()

adata.obs.drop(
            columns=['CellID', 'pxl_row_in_fullres', 'pxl_col_in_fullres'],
            inplace=True,
        )

#load metadata for sample
core_edge = pd.read_csv("scvelo_core_edge_anno/sample_2.csv")
core_edge = core_edge.tail(core_edge.shape[0] -1)
core_edge["CellID"] = core_edge["Barcode"]
core_edge.drop("Barcode", inplace=True, axis=1)
core_edge.index = core_edge["CellID"]
adata.obs = adata.obs.join(core_edge, how="left")
adata = adata[adata.obs['cluster_annotations'].isin(['core', 'edge','transitory'])]
scv.pp.filter_and_normalize(adata)
scv.pp.moments(adata)
scv.tl.recover_dynamics(adata,n_jobs = 10)
scv.tl.velocity_graph(adata)
scv.tl.velocity(adata, mode='dynamical')
scv.tl.velocity_graph(adata)
scv.tl.latent_time(adata)
scv.tl.velocity_confidence(adata)
```

However, I cannot find file "scvelo_core_edge_anno/sample_2.csv" under the data links provided in your manuscript. I am intereted in how to access this file (I think it includes disease condition as well as spatial location). I think the loom file refers to your spatial data. Thanks.

**Comment by rohitarorayyc** [comment]
Spatial locations are loaded in with the positions csv, annotations are loaded in with the core_edge csv. You are correct that the files for: positions = pd.read_csv("position_mtx/sampleB.csv") and core_edge = pd.read_csv("scvelo_core_edge_anno/sample_2.csv"). Were not provided. These were generated from the processed Seurat object. The Seurat object has the tissue position matrix as well as the cluster_annotations.

**Comment by HelloWorldLTY** [comment]
Nice. Thanks for your replies.
